service: server
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: aonifade-lam
  region: us-east-1
  stage: prod

plugins:
  - serverless-offline

functions:
  search:
    handler: src/api/search.handler
    events:
      - http:
          path: /search
          method: GET
          cors:
            origin: "*"
  artist:
    handler: src/api/artist.handler
    events:
      - http:
          path: /artist/{id}
          method: GET
          cors:
            origin: "*"
  artist-tracks:
    handler: src/api/artist-top-tracks.handler
    events:
      - http:
          path: /artist/{id}/top
          method: GET
          cors:
            origin: "*"
  album:
    handler: src/api/album.handler
    events:
      - http:
          path: /album/{id}
          method: GET
          cors:
            origin: "*"
